// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RastgeleFilm.Models;

namespace RastgeleFilm.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RastgeleFilm.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FilmAciklama")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("FilmAd")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("FilmKategori")
                        .HasColumnType("bit");

                    b.Property<double>("FilmPuan")
                        .HasColumnType("float");

                    b.Property<string>("FilmTur")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.Property<string>("VideoYolu")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.HasKey("FilmId");

                    b.ToTable("Filmler");
                });
#pragma warning restore 612, 618
        }
    }
}
