using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RastgeleFilm.Models
{
    public static class MovieRepository
    {
        private static List<Movie> movies = null;
        static MovieRepository()
        {
            movies = new List<Movie>() 
            { 
                new Movie(){FilmId=1,FilmAd="Cehennem Melekleri 1",Video="1.mp4",Resim="1.jpg",FilmPuan=8,Aciklama="The Expandables bir kiralık savaş timidir ve bu sefer ki görevleri Güney Amerika’da bir ülkeye sızarak, bu ülkenin acımasız dikatatörünü devirmektir.. Fakat görev başlar başlamaz The Expandables grubu herşeyin tam olarak göründüğü gibi olmadığını anlar ve kendilerini tehlikeli bir ihanet ağının içerisinde bulurlar. Görevlerinin tamamlanmasının engellenmesi ve masum bir insanın hayatının tehlikeye atılmasından başka The Expandables grubu daha zor bir durum olan grubun dağılma tehlikesiyle karşı karşıyadır.."},
                new Movie(){FilmId=2,FilmAd="Cehennem Melekleri 2",Video="2.mp4",Resim="2.jpg",FilmPuan=9,Aciklama="Cehennem Melekleri serisinin 2. filminde Barney Ross’un liderliğinde efsane takımı tekrar bir arada görüyoruz. Bu kez çok daha zor ve acımasız bir düşmana karşı mücadele verecek olan ekip aralarından birini kaybetmenin acısıyla intikam peşinde koşacaklar. İlk başta basit bir hesaplaşma gibi görünen hadise aralarında ki en genç üyenin öldürülmesiyle büyük bir savaşın başlangıcını ateşleyecektir…Muhteşem aksiyon ve suç filmlerinin usta yönetmeni Simon West tarafından çekimleri Amerika’da gerçekleşen Cehennem Melekleri 2 filmi Richard Wenk tarafından ele alınmış ve kurgulanmıştır. Başrollerde ise birbirinden ünlü isimler arasında en önemlileri Sylvester Stallone, Liam Hemsworth ve Randy Couture gibi oyunculardır."},
                new Movie(){FilmId=3,FilmAd="Cehennem Melekleri 3",Video="3.mp4",Resim="3.jpg",FilmPuan=10,Aciklama="2010 yılında başlayan aksiyon dolu maceramızda en zorlu göreve hazırlanın.! Barney ve Lee’nin ekibi bu kez şimdiye kadarki en zor görevi tamamlamak zorundalar. Barney’e zamanında ekibi kurması için yardım eden Cornad isimli adam şu anda silah tüccarı işi yapmaktadır ve Cornad’ın yaptığı bu pis iş tüm ekibin canını sıkar. Bu yüzden Stonebanks takımı ayırmayı kendisine amaç edinmiştir. Barney ise takımı daha da güçlendirerek genç ekip arkadaşı ile birlikte karşı hamle yapmaya hazırlanır ve ekip yeni ve daha güçlü hali ile yeniden bir araya gelir. Barney ve ekibi artık çok daha güçlü ve çok daha teknolojik aletlere sahiptir. Fakat karşılarına çıkacak kötü planlara ne kadar hazırlıklılar bundan emin değiller ve çok zorlu bir görev onları bekliyor. Aksiyon tutkunlarının en sevilen filmi olan Cehennem melekleri serisinin son filminde aksiyon filmlerinin en sevilen, en ünlü isimlerinden oluşan kadro bu kez daha da fazla genişlemiş durumdadır. 15 Ağustosta sinema salonlarında yerini alacak olan Cehennem Melekleri 3 Filmakinesi.cm farkı ile sizlerle, iyi seyirler."},
                new Movie(){FilmId=4,FilmAd="Labirent: Ölümcül Kaçış",Video="4.mp4",Resim="4.jpg",FilmPuan=7,Aciklama="Labirent Ölümcül Kaçış - The Maze Runner 2014 Film izleAsansörde uyanan ve geçmişi hakkında hiç bir şeyi hatırlamayan Thomas kendini yine kendisi gibi geçmişlerini hatırlamayan, kapalı bir çevrede yaşayan, kendi tarımlarını yapan ve kendi ürünlerini hazırlayan 30 farklı genç çocuğun içinde bulur. Bu 30 çocuk buraya 3 yıl önce gelmiştir ve Thomas onlardan bir labirentin içinde bulunduğunu ve bu labirentten hiç bir çıkış yolunun olmadığını, dahası bu labirenti koruyan ve kimsenin kaçmasına izin vermeyen ‘’Grievers’’ adı verilen cyborg canavarlar ile dolu olduğunu öğrenir. Bu otuz genç çocuk şu ana dek umutlarını kaybetmeden yaşamlarını sürdürmüşlerdir ta ki, elinde tuhaf bir not ile neredeyse komaya girmiş olan bir kız çıkıp gelene kadar. İşte bu olay gençler arasında ayrıma neden olur ve grup ellerindekiler ile bu labirentte yaşamayı sürdürmek isteyenler ve ne pahasına olursa olsun bu labirentten kurtulup eski yaşamlarına dönmek isteyenler olarak ikiye ayrılır!"},
                new Movie(){FilmId=5,FilmAd="Labirent: Alev Deneyleri",Video="5.mp4",Resim="5.jpg",FilmPuan=8,Aciklama="Maze Runner Scorch Trials 2015 filmi tanıtım afişinde de yazdığı şekliyle “Maze Savaşı daha yeni başlıyor.” Filmin ilk ayağında Maze’den kurtulan kahramanlar, tam da düzlüğe çıktıkları sırada şimdi de ıssız ve akla gelmeyen engellerin bulunduğu bir arazide hayatta kalmak için tekrar çabalamak zorundalar. Bu çabaları binbir zorlukla daha da kötü bir hal alırken kendilerinden başta yardım edecek kimsenin de bulunmayışı seyirciyi gerilimin doruklarına çıkarırken, bir an olsun azalmayan aksiyon ve harika bilim kurgu öğeleriyle de övgüleri almayı kesinlikle hak ediyor. Maze Runner Scorch Trials filmi daha gösterime girmeden filme hayat veren yeşil ışık teknolojisinin seyirci tarafından nasıl karşılanacağı merak konusu olsa da film gösterime girdikten ilk iki hafta içerisinde gelen harika yorumlar bu konuda çok iyi iş çıkarıldığını da ortaya koydu. Ayrıca Labirent 2 Alev Deneyleri filmi için söylenmesi gereken bir başka ayrıntı ise kitapta sadece tek bir labirent olmasının yanında filmde labirent sayısının fazla olması diikat çekiciydi. Ayrıca Thomas Brodie Sangster, Nathalie Emmanuel ve Aidan Gillen Game Of Thrones’in 2011 yılı sezonunda yer almalarına rağmen bu filme kadar daha önce hiç karşılaşmamaları da önemli bir ayrıntı olarak göze çarpmayı başardı. Avustralyalı aktris Adelaide Kane Brenda’nın rolü için çok istekli olmasına rağmen zamanlamasını ayarlayamadığı için rolü alamaması da oldukça dikkat çekiciydi.."},
                new Movie(){FilmId=6,FilmAd="Labirent: Son İsyan",Video="6.mp4",Resim="6.jpg",FilmPuan=9,Aciklama="Thomas bir yolunu bularak Labirent’ten kaçmayı başarır. Ancak Thomas ve arkadaşları labirentin bulunduğu tesisten de kaçması gerekir. Bir yolunu bularak bu tesisten de kaçmayı başarırlar. Büyük kaçış planının ardından W.I.C.K.E.D adındaki dünyaya kötülük saçana ve dünyayı yöneten organizasyona karşı büyük bir isyan başlatırlar. Bu direnişte şimdiye kadar W.I.C.K.E.D’e karşı en büyük direnişi sağlayan Right Hand adındaki direnişçi grupla bir araya gelirler. Direniş devam ederken Teresa, Thomas’a ihanet eder. Bu ihanetle birlikte Thomas kendisini tekrar W.I.C.K.E.D ile karşı karşıya bulur. Acımasız ve Dünya’ya kötülük ile hükmetmeye çalışan W.I.C.K.E.D, Minho’yu kaçırır. Bunun ardından Thomas ve arkadaşları bir plan yapar. Bu planın tek amacı Minho’yu W.I.C.K.E.D’in elinden kurtarmaktadır. Thomas ve arkadaşları Minho’yu kurtarmaya çalışırken birçok plan uygularken bazı kararlar alırlar. Bu kararlar sadece Minho’nun kurtuluşunu sağlamayacaktır. Aynı zamanda W.I.C.K.E.D’İN hükmettiği dünyanın da kaderini olağanüstü şekilde etkileyecek ve değiştirecektir."},
                new Movie(){FilmId=7,FilmAd="Uyumsuz 1",Video="7.mp4",Resim="7.jpg",FilmPuan=6,Aciklama="Dünya üzerindek insanlar uzak bir gelecekte beş gruba ayrılmaktadır yaşları 16 ya geldiğinde hangi gruba uyumlu ise o sınıf özelliklerini taşımaktadır. Fakat bu çocuklardan bir tanesinin beş grubada uyumlu değildir yani uyumsuzdur. Bu sebepten çocuğun kaçması gerekmektedir. Uyumsuz - Divergent full hd film izle iyiseyirler diler."},
                new Movie(){FilmId=8,FilmAd="Uyumsuz: Kuralsız",Video="8.mp4",Resim="8.jpg",FilmPuan=8,Aciklama="20 Mart 2015 tarihinde vizyona giren, orijinal adı Insurgent olan ve Türkçeye Kuralsız adıyla çevrilen film, fragmanının yayınladığı andan itibaren merakla beklenmeye başladı. Amerikan yapımı filmin başrolünde Shailene Woodley, Ansel Elgort, Theo James yer alırken filmin yönetmenlik görevini de Robert Schwentke üstleniyor. 1 saat 59 dk’lık film tahmini olarak 110.000.000 $ hasılat yaptı. Ülkemizde ise Kuralsız filmi 12 hafta vizyonda kalmış ve 320,513 kişi tarafından izlenmiştir. Kuralsız filminin senaryosu ise Brian Duffield ve Akiva Goldsman tarafından oluşturuldu. Serinin ilk filmi Uyumsuz’a göre ikinci film olan Kuralsız filmi daha çok beğeni topladı."},
                new Movie(){FilmId=9,FilmAd="Uyumsuz: Yandaş",Video="9.mp4",Resim="9.jpg",FilmPuan=9,Aciklama="Ütopik bir Dünya’da geçen hikayenin ilk filminden bu yana gerçekleşen olayların aksiyonu en çok olanlardan biri Yandaş izleyenlerin karşısına 18 Mart 2016 tarihinde çıkıyor ve yine büyük bir merak konusu oluyor. Kuralsız filminin de yönetmenliğini yapan Robert Schwentke’nin kamera arkasına geçtiği Allegiant: Part 1 filmi yine Shailene Woodley, Miles Teller ve Theo James gibi isimlerin başrolü paylaştığı, Macera, Bilim Kurgu ve Gizem öğelerini içeriyor. Tris ve Dört sistemi alt üst ettikten sonra Chicago’yu çevreleyen duvarların dışına çıkmak zorunda kalırlar ve hayatlarında ilk kez doğup büyüdükleri şehri terk edeceklerdir. Dört ve Tris’in Chicago duvarlarının ardında devam etmekte olan ve bütün insanlığın kaderini belirleyecek olan savaşta kimin tarafında olmaları gerektikleri konusunda acilen karar vermeleri gerekecektir.."}

            };
        }
        
        public static List<Movie> Movies
        {
            get { return movies; }
        }
        public static void AddMovie(Movie movie)
        {
            movies.Add(movie);
        }
        public static Movie GetById(int id)
        {
            return movies.FirstOrDefault(i => i.FilmId == id);
        }
    }
}
